version: "3.8"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13.0-rc.4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      - "./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json"

  redis:
    container_name: redis
    image: redis:7.2.4-bookworm
    command: redis-server --requirepass abcd
    ports:
      - "6379:6379"

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis

  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app worker --loglevel=INFO -P threads
    depends_on:
      - rabbitmq
      - redis
      - app

  flower:
    container_name: flower
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app flower --port=5555
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq
      - redis
      - celery_worker
      - app
